### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by ArbenKqiku** [lantanacamara/googleSheetsR#1]
Hi,

I wanted to authenticate but unfortunately the following screen appears:

![Screen Shot 2019-11-29 at 17 13 50](https://user-images.githubusercontent.com/25617032/69880711-0339c480-12cb-11ea-8d45-3700835894fb.png)

It i in German, it basically says:"The authentication for this app is temporarily disabled. The utilization of Google-Login hasn't been confirmed for this app yet".

I looked on Google and some suggest that the issue comes from the side of the creator. Could you have a look into it?

That would be wonderful. Thanks for your help! :)

Best regards,
Arben

**Comment by alberthkcheng** [comment]
Now there is a package by tidyverse for googlesheet API v4
https://github.com/tidyverse/googlesheets4
